<section class="slider-home">
    <ul class="slides">
        <li>
            <div class="slider-bg" style="background-image: url(http://placehold.it/1500x480)"></div>
        </li>
        <li>
            <div class="slider-bg" style="background-image: url(http://placehold.it/1500x480)"></div>
        </li>
        <li>
            <div class="slider-bg" style="background-image: url(http://placehold.it/1500x480)"></div>
        </li>
        <li>
            <div class="slider-bg" style="background-image: url(http://placehold.it/1500x480)"></div>
        </li>
    </ul>
</section>
