<section class="container-list-imoveis">
    <div class="subtit-section">
        <h2>Destaques de Locação</h2>
    </div>
    <ul class="row list-imoveis">
        <?php foreach ($this->widget1 as $widget1) : ?>
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="<?php echo $this->serverUrl() . BASEDIR; ?>/imoveis/detalhes/codigo/<?= $widget1['Codigo']; ?>/<?php echo $widget1['Categoria'] . '/' . $widget1['Bairro'] . '/' . $widget1['Cidade'] . '/' . (intval($widget1['Dormitorios']) > 0 ? '-' . $widget1['Dormitorios'] : '') ?>" class="list-imoveis-link">
                    <div class="list-imoveis-img" style="background-image: url(<?php echo $widget1['FotoDestaque']; ?>)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> <?php echo $widget1['Categoria']; ?>
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong><?php echo $widget1['Bairro']; ?> - <?php echo $widget1['Cidade']; ?></strong>
                        </span>
                        <?php if (intval($widget1['Dormitorios']) > 0) : ?>
                            <span class="disp-block">
                                <i class="icon-bed51"></i> <?php echo $widget1['Dormitorios']; ?> dorm.
                            </span>
                        <?php endif; ?>
                        <span class="disp-block">
                            <i class="icon-car171"></i> <?php echo $widget1['Vagas']; ?> vagas
                        </span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price"><?php echo String::asCurrency($widget1['ValorVenda']); ?></span>
                        <span class="plus">+</span>
                    </div>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="text-right">
        <a href="<?php echo $this->serverUrl() . BASEDIR;?>/imoveis/listagem?destaque=Sim&finalidade=aluguel" class="btn btn-ver-mais">VER TODOS</a>
    </div>
</section>