<section class="container-list-imoveis">
    <div class="subtit-section">
        <h2>Lançamentos</h2>
    </div>
    <ul class="row list-imoveis">
        <?php foreach ($this->widget3 as $widget3) : ?>
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="<?php echo $this->serverUrl() . BASEDIR; ?>/imoveis/detalhes/codigo/<?= $widget3['Codigo']; ?>/<?php echo $widget3['Categoria'] . '/' . $widget3['Bairro'] . '/' . $widget3['Cidade'] . '/' . (intval($widget3['Dormitorios']) > 0 ? '-' . $widget3['Dormitorios'] : '') ?>" class="list-imoveis-link list-lancamentos">
                    <div class="list-imoveis-img" style="background-image: url(<?php echo $widget3['FotoDestaque']; ?>)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> <strong><?php echo $widget3['Empreendimento']; ?></strong>
                        </span>
                    </div>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="text-right">
        <a href="<?php echo $this->serverUrl() . BASEDIR;?>/imoveis/listagem?lancamento=Sim&destinacao=venda" class="btn btn-ver-mais">VER TODOS</a>
    </div>
</section>