
    <section class="container-list-imoveis">
        <div class="subtit-section">
            <h2>Destaques de Venda</h2>
        </div>
        <ul class="row list-imoveis">
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="#" class="list-imoveis-link">
                    <div class="list-imoveis-img" style="background-image: url(http://placehold.it/1500x480)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> Apartamento
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong>Centro - São Leoppoldo</strong>
                        </span>
                        <span class="disp-block">
                            <i class="icon-bed51"></i> 02 dorm.
                        </span>
                        <span class="disp-block">
                            <i class="icon-car171"></i> 01 vaga
                        </span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">R$ 420.000,00</span>
                        <span class="plus">+</span>
                    </div>
                </a>
            </li>
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="#" class="list-imoveis-link">
                    <div class="list-imoveis-img" style="background-image: url(http://placehold.it/1500x480)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> Apartamento
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong>Centro - São Leoppoldo</strong>
                        </span>
                        <span class="disp-block">
                            <i class="icon-bed51"></i> 02 dorm.
                        </span>
                        <span class="disp-block">
                            <i class="icon-car171"></i> 01 vaga
                        </span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">R$ 420.000,00</span>
                        <span class="plus">+</span>
                    </div>
                </a>
            </li>
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="#" class="list-imoveis-link">
                    <div class="list-imoveis-img" style="background-image: url(http://placehold.it/1500x480)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> Apartamento
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong>Centro - São Leoppoldo</strong>
                        </span>
                        <span class="disp-block">
                            <i class="icon-bed51"></i> 02 dorm.
                        </span>
                        <span class="disp-block">
                            <i class="icon-car171"></i> 01 vaga
                        </span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">R$ 420.000,00</span>
                        <span class="plus">+</span>
                    </div>
                </a>
            </li>
            <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                <a href="#" class="list-imoveis-link">
                    <div class="list-imoveis-img" style="background-image: url(http://placehold.it/1500x480)"></div>
                    <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> Apartamento
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong>Centro - São Leoppoldo</strong>
                        </span>
                        <span class="disp-block">
                            <i class="icon-bed51"></i> 02 dorm.
                        </span>
                        <span class="disp-block">
                            <i class="icon-car171"></i> 01 vaga
                        </span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">R$ 420.000,00</span>
                        <span class="plus">+</span>
                    </div>
                </a>
            </li>
        </ul>
        <div class="text-right">
            <a href="#" class="btn btn-ver-mais">VER TODOS</a>
        </div>
    </section>