<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-4">
                <nav class="menu-footer">
                    <h3>Acesse nosso menu:</h3>
                    <ul>
                        <li><a href="#"><i class="icon-keyboard53"></i> HOME</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> EMPRESA</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> VENDA</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> LOCAÇÕES</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> PARCEIROS</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> SERVIÇOS</a></li>
                        <li><a href="#"><i class="icon-keyboard53"></i> CONTATO</a></li>
                    </ul>
                </nav>
            </div>

            <div class="col-xs-12 col-sm-4">
                <div class="newsletter text-center">
                    <h3>
                        <i class="icon-email5 disp-block"></i>
                        Assine nossa Newsletter:
                    </h3>

                    <form action="#" class="form-newsletter">
                        <div class="form-group text-left">
                            <label for="nome-news">Nome:</label>
                            <input type="text" id="nome-news" name="nome-news" class="form-control">
                        </div>
                        <div class="form-group text-left">
                            <label for="nome-news">E-mail:</label>
                            <input type="text" id="email-news" name="email-news" class="form-control">
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn">
                                <i class="icon-send4"></i> Enviar
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4">
                <div class="social-footer text-right">
                    <h3>Acesse nossas redes sociais:</h3>
                    <span class="disp-blockdisp-block"><span class="block"><a href="#" class="social-facebook" title="Facebook">Facebook <i class="icon-facebook2"></i></a></span>
                    <span class="disp-block"><a href="#" class="social-twitter" title="Twitter">Twitter <i class="icon-logo22"></i></a></span>
                    <span class="disp-block"><a href="#" class="social-youtube" title="YouTube">YouTube <i class="icon-youtube30"></i></a></span>
                    <span class="disp-block"><a href="#" class="social-instagram" title="Instagram">Instagram <i class="icon-instagram19"></i></a></span>
                    <span class="disp-block"><a href="#" class="social-phone" title="Ligamos para você">Ligamos para você <i class="icon-phone72"></i></a></span>
                    <span class="disp-block"><a href="#" class="social-favorito" title="Adicione seus favoritos">Adicione seus favoritos <i class="icon-star174"></i></a></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-7 address-imo">
                <img src="<?php echo $this->serverUrl() . BASEDIR;?>/res/imgs/logo-footer.png" alt="AG3 Imóveis - Nosso compromisso é a sua realização.">
                <h3>AG3 Imóveis - CRECI 22291J</h3>
                <address>Rua Independência 1248, São Leopoldo/RS - CEP 93010-004</address>
                <div class="fone">
                    <span class="social-phone"><i class="icon-phone72"></i></span>  <strong>51 3566.2999</strong>
                </div>
            </div>
            <div class="col-xs-12 col-sm-5">
                <div class="number-whats">
                    <span class="social-whatsapp"><i class="icon-socialnetwork179"></i></span>
                    <div class="disp-inline-block">
                        <strong class="disp-block">Agora também com WhatsApp!</strong>
                        51 9739.2641 | 51 9648.2623
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="copyright">
    <div class="container text-center">
        <h6>
            2015 © <strong>AG3 Imóveis</strong> - Todos os direitos reservados.
        </h6>
        <div class="gravi">
            Desenvolvido por: <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR;?>/res/imgs/logo-gravi.png" alt="Gravi"></a>
        </div>
    </div>
</div>