<header class="header">
    <div class="container">
        <div class="fl-left logo">
            <a href="<?php echo $this->serverUrl() . BASEDIR ?>"><img src="<?php echo $this->serverUrl() . BASEDIR ?>/res/imgs/logo.png" alt="AG3 Imóveis - Nosso compromisso é a sua realização." ></a>
        </div>
        <button type="button" class="open-menu"><i class="icon-menu62"></i></button>
        <div class="social">
            <a href="#" class="social-item social-facebook" title="Facebook">
                <i class="icon-facebook2"></i>
                <span>Curta a nossa página no Facebook!</span>
            </a>
            <a href="#" class="social-item social-twitter" title="Twitter">
                <i class="icon-logo22"></i>
                <span>Curta a nossa página no Facebook!</span>
            </a>
            <a href="#" class="social-item social-youtube" title="YouTube">
                <i class="icon-youtube30"></i>
                <span>Curta a nossa página no Facebook!</span>
            </a>
            <a href="#" class="social-item social-instagram" title="Instagram">
                <i class="icon-instagram19"></i>
                <span>Curta a nossa página no Facebook!</span>
            </a>
            <a href="#" class="social-item social-phone" title="Ligamos para você">
                <i class="icon-phone72"></i>
                <span>Ligamos para você</span>
            </a>
            <a href="#" class="social-item social-favorito" title="Adicione seus favoritos">
                <i class="icon-star174"></i>
                <span>Adicione seus favoritos</span>
            </a>
            <a href="#" class="social-item social-whatsapp" title="WhatsApp">
                <i class="icon-socialnetwork179"></i>
                <span>Curta a nossa página no Facebook!</span>
            </a>
        </div>
    </div>
</header>
<nav class="menu">
    <div class="container">
        <ul>
            <li class="menu-item menu-active"><a href="#">HOME</a></li>
            <li class="menu-item"><a href="#">EMPRESA</a></li>
            <li class="menu-item"><a href="#">VENDA</a></li>
            <li class="menu-item"><a href="#">LOCAÇÕES</a></li>
            <li class="menu-item"><a href="#">PARCEIROS</a></li>
            <li class="menu-item"><a href="#">SERVIÇOS</a></li>
            <li class="menu-item"><a href="#">CONTATO</a></li>
        </ul>
    </div>
</nav>