<option value="">Preço até...</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 150000) : ?> selected <?php endif; ?> value="150000">R$ 150 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 250000) : ?> selected <?php endif; ?> value="250000">R$ 250 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 350000) : ?> selected <?php endif; ?> value="350000">R$ 350 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 450000) : ?> selected <?php endif; ?> value="450000">R$ 450 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 650000) : ?> selected <?php endif; ?> value="650000">R$ 650 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 850000) : ?> selected <?php endif; ?> value="850000">R$ 850 mil</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 1000000) : ?> selected <?php endif; ?> value="1000000">R$ 1 milhao</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 1500000) : ?> selected <?php endif; ?> value="1500000">R$ 1,5 milhão</option>
<option <?php if (isset($params['valor_max']) && $params['valor_max'] == 30000000) : ?> selected <?php endif; ?> value="30000000">Mais de R$ 1,5 milhão</option>