    <option value="">Preço de...</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 50000) : ?> selected <?php endif; ?> value="50000">R$ 50 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 100000) : ?> selected <?php endif; ?> value="100000">R$ 100 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 200000) : ?> selected <?php endif; ?> value="200000">R$ 200 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 300000) : ?> selected <?php endif; ?> value="300000">R$ 300 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 400000) : ?> selected <?php endif; ?> value="400000">R$ 400 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 500000) : ?> selected <?php endif; ?> value="500000">R$ 500 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 600000) : ?> selected <?php endif; ?> value="600000">R$ 600 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 800000) : ?> selected <?php endif; ?> value="800000">R$ 800 mil</option>
    <option <?php if (isset($params['valor_min']) && $params['valor_min'] == 1000000) : ?> selected <?php endif; ?> value="1000000">R$ 1 milhão</option>
