<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Creative - Bootstrap Admin Template</title>

    <!-- Bootstrap CSS -->
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/font-awesome.min.css" rel="stylesheet" />
    <!-- full calendar css-->
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
    <!-- owl carousel -->
    <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/fullcalendar.css">
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/widgets.css" rel="stylesheet">
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/style.css" rel="stylesheet">
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/style-responsive.css" rel="stylesheet" />
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/xcharts.min.css" rel=" stylesheet">
    <link href="<?php echo $this->serverUrl() . BASEDIR ?>/adm/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->serverUrl() . BASEDIR ?>/adm/js/html5shiv.js"></script>
    <script src="<?php echo $this->serverUrl() . BASEDIR ?>/adm/js/respond.min.js"></script>
    <script src="<?php echo $this->serverUrl() . BASEDIR ?>/adm/js/lte-ie7.js"></script>
    <![endif]-->
</head>

<body>
<?php echo $this->layout()->content;?>
</body>
</html>
