<div class="container">
    <section class="view-contato">
        <div class="subtit-section">
            <h2 class="">Solicitar contato</h2>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <form id="contato-imovel" action="<?php echo $this->serverUrl() . BASEDIR; ?>/fale-conosco" method="post">
                    <div class="form-contato">
                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <label for="nome">Nome <span class="red">*</span></label>
                                <?php echo $this->form->nome?>
                            </div>
                            <div class="col-xs-12 col-md-12 form-group">
                                <label for="email">E-mail <span class="red">*</span></label>
                                <?php echo $this->form->email?>
                            </div>
                            <?php if ($this->proposta) : ?>
                                <div class="col-xs-12 col-md-7 form-group">
                                    <label for="imovel">Imóvel </label>
                                    <?php echo $this->form->imovel;?>
                                </div>
                            <?php endif; ?>
                            <div class="col-xs-12 col-md-5 form-group">
                                <label for="ddd">Telefone <span class="red">*</span></label>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <?php echo $this->form->fone?>
                                    </div>
                                </div>
                            </div>
                            <?php if ($this->subject == 'venda') : ?>
                                <input type="hidden" name="assunto" value="venda"/>
                            <?php elseif ($this->subject == 'locacao') : ?>
                                <input type="hidden" name="assunto" value="aluguel"/>
                            <?php else : ?>
                                <div class="col-xs-12 col-md-12">
                                    <div class="form-group">
                                        <label for="cidade-send">Assunto:*</label>
                                        <select name="assunto" id="assunto" class="form-control">
                                            <option value="">Escolha um assunto de seu interesse</option>
                                            <option value="vanda">Venda</option>
                                            <option value="aluguel">Aluguel</option>
                                            <option value="trabalhe-conosco">Trabalhe Conosco</option>
                                            <option value="outros">Outros</option>
                                        </select>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="col-xs-12 form-group">
                                <label for="email">Mensagem <span class="red">*</span></label>
                                <?php echo $this->form->mensagem?>
                            </div>
                            <input type="hidden" name="subject" value="contato"/>
                            <div class="col-xs-12 form-group text-right">
                                <input type="submit" value="Enviar" class="btn">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>

<div id="contato-resposta" class="modal fade" role="dialog" style="display: none;">
    <div class="modal-dialog">
        <div class="form-contato">
            <div class="title-view">
                <h3>Mensagem Enviada</h3>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    <h4 id="message"></h4>
                </div>
            </div>
        </div>
    </div>
</div>