<div class="container">
    <section class="view-institucional">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <div class="row">
                    <div class="tit-section text-center">
                        <h1>CADASTRO</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <h3>Modalidades de Locação:</h3>

                        <h4>Fiador</h4>
                        <span>Uma ou mais pessoas acordam garantir em nome de outra, a satisfazer as obrigações, caso o devedor, locatário não as cumpra. Nesta modalidade, é necessário a apresentação de um fiador com um imóvel ou mais, de acordo com o valor da locação. Estes imóveis devem estar quitados, livres de ônus, registrado em nome do pretendente a fiador, não podendo haver usufruto.  Nesta modalidade, os pretendentes (inquilino e fiador) deverão preencher as Fichas de Cadastro da imobiliária, que estão disponíveis em nosso site.</span>
                         

                        <h4>Seguro Fiança</h4>
                        <span>Elaborado mediante pagamento de um prêmio que fica sob a responsabilidade do inquilino, sendo renovado sucessivamente  enquanto durar a locação. O pretendente à locação passa por uma análise cadastral da Seguradora (Porto Seguro) e deverá ter uma renda comprovada de no mínimo 3 (três) vezes o valor do aluguel mais encargos. O seguro é parcelado em até 11X, sendo a 1ª parcela paga no ato do recebimento das chaves e as seguintes incluídas nos próximos boletos de aluguel. Este pagamento é válido por 1 (um) ano, sendo renovado anualmente. Nesta modalidade, o pretendente deverá preencher as Fichas de Cadastro da seguradora que estão disponíveis em nosso site.</span>



                        <h4>Título de Capitalização</h4>
                        <span>um pagamento único que garante ao Inquilino a locação do imóvel desejado sem qualquer burocracia, proporcionando segurança para o inquilino e para a Imobiliária/Proprietário. Sendo corrigido pela TR. O preenchimento da apólice deve ser feito na imobiliária e o pagamento feito no banco a SUL AMÉRICA. Neste caso é necessário o preenchimento da Apólice de Seguro que está disponível na Imobiliária, e os seguintes documentos:
                        1.Cópia do CPF e Registro de identidade.
                        2.Comprovante de residência.
                        3. Comprovante de renda</span>

                        <h4>Carta Fiança</h4>
                        <span>Uma pessoa jurídica presta fiança, através de um documento denominado "carta fiança", onde constam todos os compromissos assumidos. Este documento é oferecido por empresas aos seus funcionários, e deve constar no contrato social. A carta fiança deverá ser encaminhada juntamente com a documentação do candidato a locatário para ser analisada em nosso departamento de cadastro, sujeita a averiguação e aceitação do Jurídico.</span>

                        <h4>(arquivos em PDF)</h4>
                        <p><a href="http://ag3imoveis.com.br/public/res/files/proposta_pf.pdf">- Ficha Locação Pessoa Física</a></p>
                        <p><a href="http://ag3imoveis.com.br/public/res/files/proposta_pj.pdf">- Ficha Locação Pessoa Jurídica</a></p>

                    </div>
                </div>
            </div>
    </section>
</div>