<div class="container">
<section class="view-imovel">
<div class="tit-section text-center">
    <h1>Detalhes do imóvel <?php echo $this->imovel['Codigo'];?></h1>
</div>
<h1 class="name-ap"><?php echo  $this->imovel['Categoria'] . ' PARA ' . $this->imovel['Destinacao'] . ' em ' . $this->imovel['Bairro'] . ' - ' . $this->imovel['Cidade'];?></h1>
<div class="row">
    <div class="col-xs-12 col-sm-9">
        <div class="col-lg-8">
            <div class="galeria">
                <div id="img-grande" class="flexslider">
                    <ul class="slides">
                        <?php foreach($this->imovel['Foto'] as $fotos):?>
                            <li>
                                <div>
                                    <a href="<?php echo $fotos['Foto']?>" class="lightbox-galeria" rel="gallery">
                                        <img src="<?php echo $fotos['Foto']?>" alt="<?php echo $this->imovel['Categoria'] . ' - ' . $this->imovel['Bairro']?>" />
                                        <span><i class="icon-magnifier13"></i></span>
                                    </a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div id="thumbs" class="flexslider">
                    <ul class="slides">
                        <?php foreach($this->imovel['Foto'] as $fotos):?>
                            <li>
                                <img src="<?php echo $fotos['Foto']?>" alt="<?php echo $this->imovel['Categoria'] . ' - ' . $this->imovel['Bairro']?>" />
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="info-imovel">
                <div class="bg-green">
                    <div class="list-imoveis-data">
                        <span class="disp-block"><strong>Código:</strong> <label class="highlight"><?php echo $this->imovel['Codigo'];?></label></span>
                            <?php if (intval($this->imovel['Dormitorios']) > 0) : ?>
                                <span class="disp-block">
                                    <i class="icon-bed51"></i> <?php echo $this->imovel['Dormitorios'] . (intval($this->imovel['Dormitorios']) > 1 ? ' dormitórios' : ' dormitório') ?>
                                </span>
                            <?php endif; ?>
                            <?php if (intval($this->imovel['Vagas']) > 0) : ?>
                                <span class="disp-block">
                                        <i class="icon-car171"></i> <?php echo $this->imovel['Vagas'] . (intval($this->imovel['Vagas']) > 1 ? ' vagas' : ' vagas') ?>
                                    </span>
                            <?php endif; ?>
                            <?php if (intval($this->imovel['AreaTotal']) > 0) : ?>
                                <span class="disp-block">
                                    <i class="icon-rural32"></i> <strong>Área total:</strong> <?php echo  $this->imovel['AreaTotal'];?> m²
                                </span>
                            <?php endif; ?>
                            <?php if (intval($this->imovel['ValorCondominio']) > 0) : ?>
                                <span class="disp-block">
                                    <i class="icon-dollar103"></i> <strong>Condomínio:</strong> <?php echo $this->imovel['ValorCondominio'];?> m²
                                </span>
                            <?php endif; ?>
                            <?php if (intval($this->imovel['ValorIptu']) > 0) : ?>
                                <span class="disp-block">
                                    <i class="icon-dollar103"></i> <strong>IPTU:</strong> <?php echo String::asCurrency($this->imovel['ValorIptu']);?>
                                </span>
                            <?php endif; ?>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">
                            <?php echo String::asCurrency($this->imovel['ValorVenda']);?>
                        </span>
                    </div>
                </div>
                <div class="row actions-imovel">
                    <div class="col-xs-3 text-center">
                        <a href="<?php echo $this->serverUrl() . BASEDIR?>/imoveis/add-fav?codigo=<?php echo $this->imovel['Codigo']; ?>">
                            <i class="icon-star174"></i>
                            <span>Adicionar aos favoritos</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-email131"></i>
                            <span>Indique esse imóvel</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-dollar103"></i>
                            <span>Simular financiamento</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-contacts1"></i>
                            <span>Solicitar interesse</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3">
        <div class="subtit-section subtit-contato">
            <h2>Solicitar contato</h2>
        </div>
        <div class="form-contato">
            <form action="#">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="nome">Nome:*</label>
                            <input type="text" name="nome" id="nome" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="email">E-mail:*</label>
                            <input type="text" name="email" id="email" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-7">
                        <div class="form-group">
                            <label for="cidade-send">Cidade:</label>
                            <input type="text" name="cidade-send" id="cidade-send" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-5">
                        <div class="form-group">
                            <label for="cidade-send">Telefone:</label>
                            <input type="text" name="telefone" id="telefone" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="cidade-send">Assunto:*</label>
                            <select name="assunto" id="assunto" class="form-control">
                                <option value="">Escolha um assunto de seu interesse</option>
                                <option value="vanda">Venda</option>
                                <option value="aluguel">Aluguel</option>
                                <option value="trabalhe-conosco">Trabalhe Conosco</option>
                                <option value="outros">Outros</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="mensagem">Mensagem:*</label>
                            <textarea name="mensagem" id="mensagem" cols="0" rows="0" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group text-right">
                            <button type="submit" class="btn">
                                <i class="icon-send4"></i> Enviar
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="subtit-section">
    <h2>Descrição</h2>
</div>
<p><?php echo $this->imovel['Descricao'];?></p>

<?php if (count($this->imovel['Caracteristicas']) > 0) : ?>
    <div class="subtit-section">
        <h2>Características do Imóvel</h2>
    </div>
    <ul class="caracteristicas row">
        <?php foreach($this->imovel['Caracteristicas'] as $charac => $value):?>
            <?php if(strtolower($value) == 'sim'):?>
                <li class="col-xs-12 col-sm-3"><span>&bull;</span> <?php echo $charac?></li>
            <?php elseif(is_numeric($value)):?>
                <li class="col-xs-12 col-sm-3"><span>&bull;</span> <?php echo $value . ' ' . $charac?></li>
            <?php endif;?>
        <?php endforeach;?>
    </ul>
<?php endif; ?>

<?php if (count($this->imovel['InfraEstrutura']) > 0) : ?>
    <div class="subtit-section">
        <h2>Características do Condomínio</h2>
    </div>
    <ul class="caracteristicas row">
        <?php foreach($this->imovel['InfraEstrutura'] as $charac => $value):?>
            <?php if(strtolower($value) == 'sim'):?>
                <li class="col-xs-12 col-sm-3"><span>&bull;</span> <?php echo $charac?></li>
            <?php elseif(is_numeric($value)):?>
                <li class="col-xs-12 col-sm-3"><span>&bull;</span> <?php echo $value . ' ' . $charac?></li>
            <?php endif;?>
        <?php endforeach;?>
    </ul>
<?php endif; ?>

<div class="subtit-section">
    <h2>Localização do imóvel</h2>
</div>
<div id="mapa-imovel" class="map">
</div>


</section>
</div>

<script>
    GMaps.mapLatitude  = '<?php echo $this->imovel['Latitude'];  ?>';
    GMaps.mapLongitude = '<?php echo $this->imovel['Longitude']; ?>';
</script>