<div class="container">
<section class="view-imovel">
<div class="tit-section text-center">
    <h1>Detalhes do imóvel <?php echo $this->imovel['Codigo'];?></h1>
</div>
<h1 class="name-ap"><?php echo $this->imovel['Categoria'] . '-' . $this->imovel['Bairro'] . '-' . $this->imovel['Cidade'];?></h1>
<div class="row">
    <div class="col-xs-12 col-sm-9">
        <div class="col-lg-8">
            <div class="galeria">
                <div id="img-grande" class="flexslider">
                    <ul class="slides">
                        <?php foreach($this->imovel['Foto'] as $fotos):?>
                            <li>
                                <div>
                                    <a href="<?php echo $fotos['Foto']?>" class="lightbox-galeria" rel="gallery">
                                        <img src="<?php echo $fotos['Foto']?>" alt="<?php echo $this->imovel['Categoria'] . ' - ' . $this->imovel['Bairro']?>" />
                                        <span><i class="icon-magnifier13"></i></span>
                                    </a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div id="thumbs" class="flexslider">
                    <ul class="slides">
                        <?php foreach($this->imovel['Foto'] as $fotos):?>
                            <li>
                                <img src="<?php echo $fotos['Foto']?>" alt="<?php echo $this->imovel['Categoria'] . ' - ' . $this->imovel['Bairro']?>" />
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="info-imovel">
                <div class="bg-green">
                    <div class="list-imoveis-data">
                        <span class="disp-block"><strong>Código:</strong> <label class="highlight"><?php echo $this->imovel['Codigo'];?></label></span>
                            <?php if (intval($this->imovel['Dormitorios']) > 0) : ?>
                                <span class="disp-block">
                                    <i class="icon-bed51"></i> <?php echo $this->imovel['Dormitorios'] . (intval($this->imovel['Dormitorios']) > 1 ? 'dormitórios' : 'dormitório') ?>
                                </span>
                            <?php endif; ?>
                            <?php if (intval($this->imovel['Vagas']) > 0) : ?>
                                <span class="disp-block">
                                        <i class="icon-car171"></i> <?php echo $this->imovel['Vagas'] . (intval($this->imovel['Vagas']) > 1 ? 'vagas' : 'vagas') ?>
                                    </span>
                            <?php endif; ?>
                        <span class="disp-block"><strong>Área total:</strong> 105 m²</span>
                        <span class="disp-block"><strong>Condomínio:</strong> R$ 186,00</span>
                        <span class="disp-block"><strong>IPTU:</strong> R$ 105,00</span>
                    </div>
                    <div class="list-imoveis-price">
                        <span class="txt-price">R$ 420.000,00</span>
                    </div>
                </div>
                <div class="row actions-imovel">
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-star174"></i>
                            <span>Adicionar aos favoritos</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-email131"></i>
                            <span>Indique esse imóvel</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-dollar103"></i>
                            <span>Simular financiamento</span>
                        </a>
                    </div>
                    <div class="col-xs-3 text-center">
                        <a href="#">
                            <i class="icon-contacts1"></i>
                            <span>Solicitar interesse</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3">
        <div class="subtit-section subtit-contato">
            <h2>Solicitar contato</h2>
        </div>
        <div class="form-contato">
            <p class="arial">
                <i>Para aproveitar esta oportunidade, por favor, envie o formulário abaixo que um dos nossos Corretores entrará em contato.</i>
            </p>

            <form action="#">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="nome">Nome:*</label>
                            <input type="text" name="nome" id="nome" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="email">E-mail:*</label>
                            <input type="text" name="email" id="email" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-7">
                        <div class="form-group">
                            <label for="cidade-send">Cidade:</label>
                            <input type="text" name="cidade-send" id="cidade-send" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-5">
                        <div class="form-group">
                            <label for="cidade-send">Telefone:</label>
                            <input type="text" name="telefone" id="telefone" class="form-control">
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <div class="form-group">
                            <label for="cidade-send">Assunto:*</label>
                            <select name="assunto" id="assunto" class="form-control">
                                <option value="">Escolha um assunto de seu interesse</option>
                                <option value="vanda">Venda</option>
                                <option value="aluguel">Aluguel</option>
                                <option value="trabalhe-conosco">Trabalhe Conosco</option>
                                <option value="outros">Outros</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="mensagem">Mensagem:*</label>
                            <textarea name="mensagem" id="mensagem" cols="0" rows="0" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group text-right">
                            <button type="submit" class="btn">
                                <i class="icon-send4"></i> Enviar
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="subtit-section">
    <h2>Descrição</h2>
</div>
<p>Apartamento de 2 dormitórios, mobiliado, bem localizado. Confira!</p>

<div class="subtit-section">
    <h2>Características do Imóvel</h2>
</div>
<ul class="caracteristicas row">
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Ar Condicionado</li>
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Área Serviço</li>
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Churrasqueira</li>
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Mobiliado</li>
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Sacada</li>
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Cozinha</li>
</ul>

<div class="subtit-section">
    <h2>Características do Condomínio</h2>
</div>
<ul class="caracteristicas row">
    <li class="col-xs-12 col-sm-3"><span>&bull;</span> Gás Central</li>
</ul>

<div class="subtit-section">
    <h2>Localização do imóvel</h2>
</div>
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d56621.19651969154!2d-48.6548185!3d-27.505824199999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spt-BR!2sbr!4v1452347028046" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>


</section>
</div>

<script>
    GMaps.mapLatitude  = '<?php echo $this->imovel['Latitude'];  ?>';
    GMaps.mapLongitude = '<?php echo $this->imovel['Longitude']; ?>';
</script>