<div class="container">
    <?php echo $this->partial('index/busca_form.phtml', array(
        'listas' => $this->listas,
        'innerDivClass' => 'pesquisa-imoveis',
        'buttonText' => 'Buscar novamente',
    )); ?>

    <section class="resultado-busca">
        <div class="title-section">
            <h2 class="title-section-text"><?php echo $this->title; ?></h2>
        </div>
        <div class="row">
            <div class="col-xs-12 col-lg-12">
                <ul class="row list-imoveis">
                    <?php if (count($this->imoveis) > 0) : foreach ($this->imoveis as $imovel) : ?>
                        <li class="col-xs-12 col-sm-6 col-md-3 list-imoveis-item">
                            <a href="<?php echo $this->serverUrl() . BASEDIR; ?>/imoveis/detalhes/codigo/<?= $imovel['Codigo']; ?>/<?php echo $imovel['Categoria'] . '/' . $imovel['Bairro'] . '/' . $imovel['Cidade'] . '/' . (intval($imovel['Dormitorios']) > 0 ? '-' . $imovel['Dormitorios'] : '') ?>" class="list-imoveis-link">
                                <div class="list-imoveis-img" style="background-image: url(<?php echo $imovel['FotoDestaque']; ?>)"></div>
                                <div class="list-imoveis-data">
                        <span class="disp-block">
                            <i class="icon-city33"></i> <?php echo $imovel['Categoria']; ?>
                        </span>
                        <span class="disp-block">
                            <i class="icon-situation"></i> <strong><?php echo $imovel['Bairro']; ?> - <?php echo $imovel['Cidade']; ?></strong>
                        </span>
                                    <?php if (intval($imovel['Dormitorios']) > 0) : ?>
                                        <span class="disp-block">
                                <i class="icon-bed51"></i> <?php echo $imovel['Dormitorios']; ?> dorm.
                            </span>
                                    <?php endif; ?>
                                    <span class="disp-block">
                            <i class="icon-car171"></i> <?php echo $imovel['Vagas']; ?> vagas
                        </span>
                                </div>
                                <div class="list-imoveis-price">
                                    <span class="txt-price"><?php echo String::asCurrency($imovel['ValorVenda']); ?></span>
                                    <span class="plus">+</span>
                                </div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                    <?php else : ?>
                        <section class="view-imovel">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="text-center">
                                        <h2>Nenhum imóvel encontrado com esta pesquisa</h2>
                                    </div>
                                </div>
                            </div>
                        </section>
                    <?php endif; ?>
                </ul>
                <ul class="paginacao">

                    <!-- Previous -->
                    <?php if(isset($this->pagination->previous)):?>
                        <?php $this->params['page'] = $this->pagination->previous?>
                        <li class="paginacao-item with-arrow"><a href="<?php echo $this->serverUrl() . BASEDIR;?>/imoveis/listagem?<?php echo http_build_query($this->params); ?>"><i class="icon-left216"></i></a></li>
                    <?php else:?>
                        <li class="paginacao-item with-arrow disabled"><a href="#"><i class="icon-left216"></i></a></li>
                    <?php endif;?>

                    <!-- Pages List -->
                    <?php foreach($this->pagination->pagesInRange as $page):?>
                        <?php if($page == $this->pagination->current):?>
                            <li class="paginacao-item"><a href="#" class="active"><?php echo $page; ?></a></li>
                        <?php else:?>
                            <?php $this->params['page'] = $page?>
                            <li class="paginacao-item"><a href="<?php echo $this->serverUrl() . BASEDIR;?>/imoveis/listagem?<?php echo http_build_query($this->params); ?>"><?php echo $page?></a></li>
                        <?php endif;?>
                    <?php endforeach;?>

                    <!-- Next -->
                    <?php if(isset($this->pagination->next)):?>
                        <?php $this->params['page'] = $this->pagination->next?>
                        <li class="paginacao-item with-arrow"><a href="<?php echo $this->serverUrl() . BASEDIR;?>/imoveis/listagem?<?php echo http_build_query($this->params); ?>"><i class="icon-keyboard53"></i></a></li>
                    <?php else:?>
                        <li class="paginacao-item with-arrow disabled"><a href="#"><i class="icon-keyboard53"></i></a></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </section>
</div>