<div class="subtit-section">
    <h2>Imóveis semelhantes</h2>
</div>
<ul class="list-semelhantes row">
    <?php foreach ($this->semelhantes as $semelhante) : ?>
    <li class="col-xs-12 col-sm-6 col-md-3 semelhantes-item">
        <a href="" class="semelhantes-link">
            <div class="list-imoveis-img" style="background-image: url(<?php echo $semelhante['FotoDestaque']; ?>)"><span><i class="icon-add182"></i></span></div>
            <div class="list-imoveis-data">
                <p>
                    <?php echo $semelhante['Categoria']; ?> <br>
                    <?php echo $semelhante['Bairro'] . ' - ' . $semelhante['Cidade']; ?>
                </p>
                <h3><?php echo String::asCurrency($semelhante['ValorVenda']); ?></h3>
            </div>
        </a>
    </li>
    <?php endforeach; ?>
</ul>