<div class="container">
    <section class="view-institucional">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <div class="row">
                    <div class="tit-section text-center">
                        <h1>SIMULADORES</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="https://www.google.com.br/search?sclient=psy-ab&btnG=Search&q=financiamento+caixa+federal#q=financiamento+banco+do+brasil+simulador">
                                    <img src="http://ipeimobiliaria.com.br/img/bb.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="http://www8.caixa.gov.br/siopiinternet/simulaOperacaoInternet.do?method=inicializarCasoUso">
                                    <img src="http://financiamento-online.com/img/simulador-de-financiamento-imobiliario-caixa/faca-a-simulacao-de-financiamento-imobiliario-caixa-aqui.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="http://www.shopcredit.com.br/shopcredit/br/stsm/stsmtipocredimob.asp?layout=F&amp;retorno=simulador&amp;strPerfil=1&amp;strProduto=4&amp;strModeloSimulador=5">
                                    <img src="http://ativaimob.com.br/wp-content/uploads/2012/06/banner_simulador_bradesco.jpg" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="http://www.banrisul.com.br/brz/link/brzw01hw.asp?css=bob&secao_id=1083">
                                    <img src="http://www.banrisul.com.br/bob/data/img_BANNER/1069.gif" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="https://www.itau.com.br/creditos-financiamentos/imoveis/simulador/">
                                    <img src="http://www.imobiliariahaus.com.br/img/itau.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="https://wwws3.hsbc.com.br/HPB-CHM-SIMULADOR/servlets/HPBCreditoImobiliarioServlet">
                                    <img src="http://www.creditooudebito.com.br/wp-content/uploads/2013/01/hsbc-financiamento.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="simulador-img">
                                <a href="https://www.santander.com.br/br/resolva-on-line/simuladores/credito-imobiliario">
                                    <img src="http://www.creditooudebito.com.br/wp-content/uploads/2013/01/financiamento-santander-e1357901039942.jpg" alt=""/>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</div>