<div class="container">
    <section class="view-conteudo">
        <div class="tit-section text-center">
            <h1>Conheça nossos parceiros</h1>
        </div>
        <p class="arial">
            A AG3 Imoveis consolidou ao longo de sua trajetória parcerias com fornecedores, construtoras, incorporadores e clientes em ações comerciais e sociais. Abaixo alguns dos nossos parceiros.
        </p>

        <p>
            <a href="#texto" class="lightbox">Exemplo de lightbox com texto</a>
        </p>

        <div id="texto" style="display: none;">
            <p class="arial text-center">Você adicionou esse imóvel como um de seus favoritos!</p>
        </div>


        <ul class="list-parceiros row">
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="http://placehold.it/300x200" class="img-responsive" /></a>
            </li>
        </ul>

        <div class="tit-section text-center">
            <h1>Responsabilidade Social</h1>
        </div>
        <p>
            A AG3 Imóveis tem construído ao longo dos anos, uma prática permanente de responsabilidade social. O tema está presente na atitude e na atuação da empresa por meio de relações éticas e duradouras com clientes, fornecedores, colaboradores e parceiros.
        </p>
        <p>Com o objetivo de colaborar para minimizar as enormes carências e desigualdades existentes na cidade, a AG3 criou o movimento TRIBO DO ABRAÇO.</p>
        <p>A TRIBO DO ABRAÇO desenvolve ações sociais e de cidadania, focando sua atuação na mobilização solidária. Contando sempre com outros empresários parceiros, a Tribo do Abraço realiza todo ano o Natal Solidário e a Campanha do Agasalho.</p>
        <p>Saiba mais acessando: <a href="#">www.tribodoabracoag3.blogspot.</a></p>

    </section>
</div>