<div class="container">
    <section class="view-conteudo">
        <div class="tit-section text-center">
            <h1>Conheça nossos parceiros</h1>
        </div>
        <p class="arial">
            A AG3 Imoveis consolidou ao longo de sua trajetória parcerias com fornecedores, construtoras, incorporadores e clientes em ações comerciais e sociais. Abaixo alguns dos nossos parceiros.
        </p>

        <ul class="list-parceiros row">
            <li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/acis_90_anos.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/aessul.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/akso.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/arquipelago_viagens.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/benin.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/body_sull.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/cisplan.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/construesse.jpg" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/cruz_vermelha.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/embratec.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/fc_equilibrio.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/feltes.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/gerencial.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/logo_baliza.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/logo_kaefe.jpg" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/logo_nex.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/marketing_imob.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/marselha.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/mavel.bmp" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/oliva.jpg" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/pilates.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/planta_e_obra.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/prefeitura_sao_leopoldo.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/stihl.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/studio_m.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/sturmer.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/sulsoftware.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/tevah.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/ughini.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/vista.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/vs.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/weissheimer.jpg" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/wuttke.gif" class="img-responsive" /></a>
            </li><li class="col-xs-6 col-sm-4 col-lg-3">
                <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/parceiros/zipimobi.gif" class="img-responsive" /></a>
            </li>
        </ul>

    </section>
</div>