<div class="container">
    <section class="view-institucional">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <div class="row">
                    <div class="tit-section text-center">
                        <h1>AG3 Imóveis</h1>
                    </div>
                </div>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3463.246974878201!2d-51.14674848431634!3d-29.770499325550407!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95196851171871bd%3A0x2cf6480697104d77!2sA+G+3+Im%C3%B3veis!5e0!3m2!1sen!2sbr!4v1469715995453" width="100%" height="650" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </section>
</div>