<div class="col-xs-12 col-sm-6 col-lg-6">
    <div class="profile-card">
        <div class="col-sm-4 text-left profile-box">
            <div class="profile-img">
                <img class="" src="<?php echo ($this->user['Foto'] != '' ? $this->user['Foto'] : $this->serverUrl() . BASEDIR . '/res/imgs/no-profile.jpg');?>">
            </div>
        </div>
        <div class="col-sm-8 profile-info">
            <div class="col-sm-12 text-left  profile-box">
                <span class="emp-name"><?php echo $this->user['Nome']; ?></span>
            </div>
            <div class="col-sm-12 text-left  profile-box">
                <span><?php echo $this->user['E-mail']; ?></span>
            </div>
            <?php if ($this->user['Fone'] != '') : ?>
                <div class="col-sm-12 text-left  profile-box">
                    Fone:<span> <?php echo $this->user['Fone']; ?></span>
                </div>
            <?php endif; ?>
            <?php if ($this->user['CRECI'] != '') : ?>
                <div class="col-sm-12 text-left  profile-box">
                    CRECI:<span> <?php echo $this->user['CRECI']; ?></span>
                </div>
            <?php endif; ?>
            <div class="img-wm">
                <img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/logo-tree.png" />
            </div>
        </div>
    </div>
</div>