
<div class="container">
    <section class="view-institucional">
        <div class="row text-justify">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <div class="row">
                    <div class="tit-section text-center">
                        <h1>Equipe AG3 Imóveis</h1>
                    </div>
                    Atuando na Intermediação de compra e venda, na Administração de aluguéis de imóveis,
                    <span>Gestão de negócios, Consultorias e Avaliações</span>,
                    a AG3 IMÓVEIS conta com uma equipe de profissionais, assessores e funcionários que aliam a experiência de mais de quarenta anos de atuação no mercado
                    imobiliário de São Leopoldo e Vale dos Sinos, com o entusiasmo, o dinamismo e as ferramentas de gestão hoje disponíveis.</span>
                    <span></span>
                    <span>
                <hr>
                        <br>Visão</span>
                    <br>Ser reconhecida no setor imobiliário pela eficiência e atendimento especializado, destacando-se por equipes motivadas, comprometidas com a satisfação dos clientes e com a comunidade.<br>
                    <span>
                        <br>Missão<br></span><br>Fornecer produtos e serviços adequados às necessidades e interesses de seus clientes, buscando o contínuo aprimoramento e atuando de forma segura e rentável, com responsabilidade social e ambiental.<br>
                       <span>
                    <br>Valores<br><br></span>• Conhecimento<br>• Credibilidade<br>• Transparência<br>• Responsabilidade<br>• Pluralidade<br>• Respeito e Desenvolvimento de Pessoas<br><br>Esperamos, através de nosso SITE, contribuir na concretização de negócios de nossos clientes.
                </div>
            </div>
        </div>
    </section>
</div>