
<div class="container">
    <section class="view-institucional">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-lg-12">

                <div class="tit-section text-center">
                    <h1>Equipe AG3 Imóveis</h1>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php foreach ($this->users as $group => $users) : ?>
                            <div class="col-lg-12">
                                <h2 class="title-view-small"><?php echo $group; ?></h2>
                                <?php foreach ($users as $user) : ?>
                                    <?php echo $this->partial('quem-somos/card.phtml', array('user' => $user)); ?>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

